# Generated by Django 6.0.7 on 2026-07-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read after reviewing')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(help_text='e.g. Bachelor of Science', max_length=100)),
                ('field_of_study', models.CharField(help_text='e.g. Computer Science', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if you are currently studying here')),
                ('grade', models.CharField(blank=True, help_text='e.g. GPA: 3.8/4.0', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only active entries are shown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('company_website', models.URLField(blank=True)),
                ('description', models.TextField(help_text='Job responsibilities and achievements')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current position')),
                ('is_active', models.BooleanField(default=True, help_text='Only active entries are shown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('title', models.CharField(help_text="Professional title, e.g. 'Full Stack Developer'", max_length=100)),
                ('bio', models.TextField(help_text='Short biography / about me text')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, help_text='Upload your CV/resume', null=True, upload_to='profile/')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('stackoverflow_url', models.URLField(blank=True, help_text='Stack Overflow profile URL')),
                ('dribbble_url', models.URLField(blank=True, help_text='Dribbble profile URL')),
                ('available_for_work', models.BooleanField(default=True, help_text='Whether you are currently available for new opportunities')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active profile is shown on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief description shown in project cards', max_length=300)),
                ('description', models.TextField(help_text='Full project description')),
                ('project_image', models.ImageField(blank=True, help_text='Main project image / screenshot', null=True, upload_to='projects/')),
                ('project_url', models.URLField(blank=True, help_text='Live demo URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project on the home page')),
                ('is_active', models.BooleanField(default=True, help_text='Only active projects are shown')),
                ('date_completed', models.DateField(blank=True, help_text='When the project was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class, e.g. 'fas fa-code'", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only active services are shown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=50, help_text='Proficiency percentage (0-100)')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class, e.g. 'fab fa-python'", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this skill prominently on the home page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='e.g. Senior Developer', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(help_text='Testimonial text')),
                ('image', models.ImageField(blank=True, help_text='Photo of the person', null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials are shown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Technologies used in this project', related_name='projects', to='main.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory'),
        ),
    ]
