# Generated by Django 6.0.7 on 2026-07-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
