# Generated by Django 6.0.7 on 2026-07-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_skill_category_remove_skill_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='available_for_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dribbble_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stackoverflow_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail_address',
            field=models.EmailField(blank=True, help_text='Gmail address', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='leetcode_url',
            field=models.URLField(blank=True, help_text='LeetCode profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=30),
        ),
    ]
