# Generated by Django 6.0.7 on 2026-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_available_for_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='project_media',
            field=models.FileField(blank=True, help_text='Image or video file for this project', null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(blank=True, help_text='Describe the technologies used in this project'),
        ),
    ]
