# Generated by Django 6.0.7 on 2026-07-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_options_remove_profile_twitter_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_active',
        ),
    ]
