# Generated by Django 6.0.7 on 2026-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_experience_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, help_text="Company name (e.g. 'Acme Corp')", max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload company logo (e.g. logo.png)', null=True, upload_to='profile/'),
        ),
    ]
