# Generated by Django 6.0.7 on 2026-07-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_company_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=200, unique=True),
        ),
    ]
