# Generated by Django 4.2.25 on 2026-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated if left blank)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=200, null=True, unique=True),
        ),
    ]
