# Generated by Django 6.0.7 on 2026-07-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_experience_slug_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="icon_color",
            field=models.CharField(
                blank=True,
                help_text="Hex color for the icon, e.g. '#306998' for Python blue",
                max_length=7,
            ),
        ),
    ]
