# Generated by Django 6.0.7 on 2026-07-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_skill_icon_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="icon_color",
        ),
    ]
